Update docker-image-deps.yml

diff --git a/.github/workflows/docker-image-deps.yml b/.github/workflows/docker-image-deps.yml
--- a/.github/workflows/docker-image-deps.yml
+++ b/.github/workflows/docker-image-deps.yml
@@ -34,7 +34,27 @@ jobs:
 
           uname -m
 
-          docker buildx build --load --tag wheels --build-arg NUMPY_VER=${{ env.NUMPY_VER }} --build-arg PANDAS_VER=${{ env.PANDAS_VER }} --build-arg AV_VER=${{ env.AV_VER }} --build-arg CRYPTOGRAPHY_VER=${{ env.CRYPTOGRAPHY_VER }} --build-arg UV_VER=${{ env.UV_VER }} --platform linux/arm/v5 --allow security.insecure --no-cache -f ./deps/Dockerfile .
+          export LINK=$(curl --silent https://api.github.com/repos/rara64/armv5-homeassistant/actions/artifacts | jq -r '.artifacts[] | select(.name == "maturin") | .archive_download_url' | head -n 1)
+          curl -L -H "Authorization: token ${{ secrets.WHEELS_TOKEN }}" -o maturin.zip "$LINK" || echo 'deps download failed'
+          7z e maturin.zip -o./maturin -y || echo 'maturin extract failed'
+
+          export MATURIN_VER=$(curl -s https://pypi.org/pypi/maturin/json | jq -r '.info.version')
+          export MATURIN_BUILD_VER=$(cat ./maturin/maturin_ver.txt)
+          export OUTDATED_MATURIN=0
+          if [[ "${MATURIN_VER}" != "${MATURIN_BUILD_VER}" ]]; then
+            export OUTDATED_MATURIN=1
+            echo "OUTDATED_MATURIN=$OUTDATED_MATURIN" >> $GITHUB_ENV
+            echo "Outdated Maturin! Expected: ${MATURIN_VER} Got: ${MATURIN_BUILD_VER}"
+            exit 0
+          fi
+          echo "OUTDATED_MATURIN=$OUTDATED_MATURIN" >> $GITHUB_ENV
+          export MATURIN_PATH = ${find *.whl ./maturin}
+
+          docker buildx build --load --tag wheels --build-arg NUMPY_VER=${{ env.NUMPY_VER }} --build-arg MATURIN=$MATURIN_PATH --build-arg PANDAS_VER=${{ env.PANDAS_VER }} --build-arg AV_VER=${{ env.AV_VER }} --build-arg CRYPTOGRAPHY_VER=${{ env.CRYPTOGRAPHY_VER }} --build-arg UV_VER=${{ env.UV_VER }} --platform linux/arm/v5 --allow security.insecure --no-cache -f ./deps/Dockerfile .
+      - name: Dispatch maturin build
+        if: ${{ env.OUTDATED_MATURIN == 1 }}
+        run : |
+          curl -XPOST -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.WHEELS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/rara64/armv5-homeassistant/dispatches --data '{"event_type": "Build maturin for armv5-homeassistant"}'
       - name: Extract wheels
         if: ${{ env.WHEELS_NEEDED == '0' }}
         shell: bash
