Update docker-image-deps2.yml

diff --git a/.github/workflows/docker-image-deps2.yml b/.github/workflows/docker-image-deps2.yml
--- a/.github/workflows/docker-image-deps2.yml
+++ b/.github/workflows/docker-image-deps2.yml
@@ -46,6 +46,30 @@ jobs:
           export LINK=$(curl --silent https://api.github.com/repos/rara64/armv5-homeassistant/actions/artifacts | jq -r '.artifacts[] | select(.name == "deps") | .archive_download_url' | head -n 1)
           curl -L -H "Authorization: token ${{ secrets.WHEELS_TOKEN }}" -o deps.zip "$LINK" || echo 'deps download failed'
 
+          export LINK=$(curl --silent https://api.github.com/repos/rara64/armv5-homeassistant/actions/artifacts | jq -r '.artifacts[] | select(.name == "maturin") | .archive_download_url' | head -n 1)
+          curl -L -H "Authorization: token ${{ secrets.WHEELS_TOKEN }}" -o maturin.zip "$LINK" || echo 'deps download failed'
+          7z e maturin.zip -o./maturin -y || echo 'maturin extract failed'
+
+          export MATURIN_VER=$(curl -s https://pypi.org/pypi/maturin/json | jq -r '.info.version')
+          export MATURIN_BUILD_VER=$(cat ./maturin/maturin_ver.txt)
+          export OUTDATED_MATURIN=0
+          if [[ "${MATURIN_VER}" != "${MATURIN_BUILD_VER}" ]]; then
+            export OUTDATED_MATURIN=1
+            echo "OUTDATED_MATURIN=$OUTDATED_MATURIN" >> $GITHUB_ENV
+            echo "Outdated Maturin! Expected: ${MATURIN_VER} Got: ${MATURIN_BUILD_VER}"
+            exit 0
+          fi
+          echo "OUTDATED_MATURIN=$OUTDATED_MATURIN" >> $GITHUB_ENV
+
+          find ./maturin -name "*.whl" -print0 | while IFS= read -r -d $'\0' file; do
+            if [ -f "$file" ]; then
+              new_name=$(echo "$file" | sed 's/armv5tel/armv7l/g')
+              if [ "$file" != "$new_name" ]; then
+                mv -v "$file" "$new_name"
+              fi
+            fi
+          done
+
           docker buildx build --load --tag wheels \
           --build-arg ANTHROPIC_VER=${{ env.ANTHROPIC_VER }} \
           --build-arg DEEBOT_VER=${{ env.DEEBOT_VER }} \
@@ -55,7 +79,12 @@ jobs:
           --build-arg ZEROCONF_VER=${{ env.ZEROCONF_VER }} \
           --build-arg MATRIX_VER=${{ env.MATRIX_VER }} \
           --build-arg DEPS="deps.zip" \
+          --build-arg MATURIN=$(MATURIN) \
           --platform linux/arm/v5 --allow security.insecure --no-cache -f ./deps2/Dockerfile .
+      - name: Dispatch maturin build
+        if: ${{ env.OUTDATED_MATURIN == 1 }}
+        run : |
+          curl -XPOST -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.WHEELS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/rara64/armv5-homeassistant/dispatches --data '{"event_type": "Build maturin for armv5-homeassistant"}'
       - name: Extract wheels
         if: ${{ env.WHEELS_NEEDED == '0' }}
         shell: bash
