Update docker-image-arm.yml

diff --git a/.github/workflows/docker-image-arm.yml b/.github/workflows/docker-image-arm.yml
--- a/.github/workflows/docker-image-arm.yml
+++ b/.github/workflows/docker-image-arm.yml
@@ -26,11 +26,11 @@ jobs:
         run: |
           export LINK=$(curl --silent https://api.github.com/repos/rara64/armv5-homeassistant/actions/artifacts | jq -r '.artifacts[] | select(.name == "deps") | .archive_download_url' | head -n 1)
           curl -L -H "Authorization: token ${{ secrets.WHEELS_TOKEN }}" -o deps.zip "$LINK" || echo 'deps download failed'
-          7z x deps.zip -o./deps -y || echo 'deps extract failed'
+          7z e deps.zip -o./deps -y || echo 'deps extract failed'
 
           export LINK=$(curl --silent https://api.github.com/repos/rara64/armv5-homeassistant/actions/artifacts | jq -r '.artifacts[] | select(.name == "deps2") | .archive_download_url' | head -n 1)
           curl -L -H "Authorization: token ${{ secrets.WHEELS_TOKEN }}" -o deps2.zip "$LINK" || echo 'deps download failed'
-          7z x deps2.zip -o./deps -y || echo 'deps2 extract failed'
+          7z e deps2.zip -o./deps -y || echo 'deps2 extract failed'
 
           # GET CURRENT VERSION OF DEPS
           export TAG=$(curl --silent https://api.github.com/repos/home-assistant/core/releases | jq -r 'map(select(.prerelease==false)) | first | .tag_name')
@@ -72,6 +72,13 @@ jobs:
           7z a filtered_deps.zip ./deps/* || echo 'deps repack failed'
           mv filtered_deps.zip deps.zip
 
+          WHEELS_LIST=('ELEVENLABS' 'ANTHROPIC')
+          
+          for wheel in "${WHEELS_LIST[@]}"; do 
+            VER=$(cat ./deps/versions.txt | grep -m 1 -i "${wheel}" | awk -F'=' '{print $NF}' | tr -d '\n')
+            export ${wheel}_VER="${VER:-0}"
+          done
+
           # COMPARE VERSIONS OF DEPS
           OUTDATED_DEPS=0
           OUTDATED_DEPS_2=0
@@ -80,7 +87,7 @@ jobs:
             w=${wheel}_VER
             if [[ "${!wh}" != "${!w}" ]]; then
               case "${wheel}" in
-                PYNACL|ZEROCONF|ORJSON|DEEBOT)
+                PYNACL|ZEROCONF|ORJSON|DEEBOT|ANTHROPIC|ELEVENLABS)
                   OUTDATED_DEPS_2=1
                   break
                   ;;
@@ -89,6 +96,7 @@ jobs:
               break
             fi
           done
+          
 
           export OUTDATED_DEPS
           export OUTDATED_DEPS_2
