Update docker-image-wheels3.yml

diff --git a/.github/workflows/docker-image-wheels3.yml b/.github/workflows/docker-image-wheels3.yml
--- a/.github/workflows/docker-image-wheels3.yml
+++ b/.github/workflows/docker-image-wheels3.yml
@@ -39,16 +39,21 @@ jobs:
       - name: Register qemu-arm with binfmt_misc
         run: |
           sudo update-binfmts --enable qemu-arm
-
       - name: Create custom entry point for qemu-arm-static
         run: |
           echo '#!/bin/bash' | sudo tee /usr/bin/qemu-arm-custom
           echo '/usr/bin/qemu-arm-static -cpu arm926ej-s "$@"' | sudo tee -a /usr/bin/qemu-arm-custom
           sudo chmod +x /usr/bin/qemu-arm-custom
 
-      - name: Add qemu-arm-custom to qemu-arm config file
+      - name: Find and modify qemu-arm interpreter path
         run: |
-          sudo sed -i 's|/usr/bin/qemu-arm-static|/usr/bin/qemu-arm-custom|g' /var/lib/binfmts/qemu-arm
+          INTERPRETER_PATH=$(find /proc/sys/fs/binfmt_misc -name 'qemu-arm' -print -quit)
+          if [ -n "$INTERPRETER_PATH" ]; then
+            sudo sed -i 's|/usr/bin/qemu-arm-static|/usr/bin/qemu-arm-custom|g' "$INTERPRETER_PATH"
+          else
+            echo "Error: Could not find qemu-arm interpreter path in /proc/sys/fs/binfmt_misc"
+            exit 1
+          fi
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       - name: Build and load the image
