Update docker-image-arm.yml

diff --git a/.github/workflows/docker-image-arm.yml b/.github/workflows/docker-image-arm.yml
--- a/.github/workflows/docker-image-arm.yml
+++ b/.github/workflows/docker-image-arm.yml
@@ -21,7 +21,7 @@ jobs:
       - name: Check for new version of deps
         run: |
           export LINK=$(curl --silent https://api.github.com/repos/rara64/armv5-homeassistant/actions/artifacts | jq -r '.artifacts[] | select(.name == "deps") | .archive_download_url' | head -n 1)
-          wget -O deps.zip $(curl -I -H "Authorization: token ${{ secrets.WHEELS_TOKEN }}" $LINK | grep location: | cut -d: -f2-) || echo 'deps download failed'
+          curl -L -H "Authorization: token ${{ secrets.WHEELS_TOKEN }}" -o deps.zip "$LINK" || echo 'deps download failed'
           7z x deps.zip -o ./deps || echo 'deps extract failed'
           
           # GET CURRENT VERSION OF DEPS
